# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6accb553f67bd2f56f8a39150178340f800959e0474d715db0ad1e56f137bcd7ebbf114a9519e0e4581f52f02615d1014b78fdaddc7882b64f2d1cdb2c745d2a

test:
  secret_key_base: 01fb1d48ddc13a38192085c04cc72d559c8f21fefebe490c160e57a8fcc3599393809a24fb7d5f0b157020d265d2123e4f6bf93c324ebb4ad04460ffad957e03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
